---
title: "DE analysis revised"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#raw counts were downloaded using the TCGABioLinks R package, the cleaned rds object from which is uploaded to Figshare at :
#counts = readRDS("Data/cleaned_RNAseq_counts.rds")

#get phenotype data
pheno = data.table::fread("Data/tcga_clinical_data.tsv")

#filter to observations with phenotype data
colnames(counts) = unlist(lapply(colnames(counts), function(x){
  stringr::str_sub(x, 1, 15)
}))

inds = which(colnames(counts) %in% pheno$`Sample ID`)
counts2 = counts[,inds]
```


EdgeR
```{r}
library(edgeR)

d = DGEList(counts2)

#filter low expressed genes
keep = filterByExpr(d)
d = d[keep, , keep.lib.sizes = FALSE]

d = calcNormFactors(d)

#sort phenotype information to make age groups
PhenoFilt = pheno[which(pheno$`Sample ID` %in% colnames(counts2)),]
PhenoSorted = PhenoFilt[match(colnames(counts2), PhenoFilt$`Sample ID`),]


#remove observations without age data
d1 = d[, -which(is.na(PhenoSorted$`Diagnosis Age`))]


PhenoSorted = PhenoSorted[-which(is.na(PhenoSorted$`Diagnosis Age`)),]

mm = model.matrix(~PhenoSorted$`Diagnosis Age` + PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym`)

y = voom(d1, mm, plot = T)

fit = lmFit(y, mm)

tmp = contrasts.fit(fit, coef = 2) 
tmp = eBayes(tmp)
top.table = topTable(tmp, sort.by = "P", n = Inf)
head(top.table, 20)

TCGADE = top.table
```


Include TMB

```{r}
d1 = d1[, -which(is.na(PhenoSorted$`Mutation Count`))]

PhenoSorted = PhenoSorted[-which(is.na(PhenoSorted$`Mutation Count`)),]

mm = model.matrix(~PhenoSorted$`Diagnosis Age` + PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym` + log(PhenoSorted$`Mutation Count`))

y = voom(d1, mm, plot = T)

fit = lmFit(y, mm)

tmp = contrasts.fit(fit, coef = 2) 
tmp = eBayes(tmp)
top.table = topTable(tmp, sort.by = "P", n = Inf)
head(top.table, 20)

TCGADETMBAdj = top.table
```


GTex

```{r}
# download GTEx version 8 at https://gtexportal.org/home/datasets ***
# gtexCounts = phantasus::read.gct(gzfile("Data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz"))

#read in phenotype data
subjectAnn = data.table::fread("Data/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt")
summary(as.factor(subjectAnn$AGE))

sampleAnn = data.table::fread("Data/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
sampleAnnSub = sampleAnn[, c(1,6,7)]

summary(as.factor(sampleAnn$SMAFRZE))
sampleAnnSub = sampleAnnSub[which(sampleAnn$SMAFRZE == "RNASEQ"),]
summary(as.factor(sampleAnnSub$SMTS))

#format and normalize RNA-seq data
#check row and column names
library(SummarizedExperiment)
gtexMatrix = exprs(gtexCounts)

#remove 20-29 ages
sampleAnnSub$SubjectID = unlist(lapply(sampleAnnSub$SAMPID, function(x){
  strs = stringr::str_split(x, "-")[[1]][c(1,2)]
  out = paste(strs[1], strs[2], sep = "-")
  return(out)
}))

ages = vector(mode = "character", nrow(sampleAnnSub))
for(i in seq(nrow(sampleAnnSub))) {
  ages[i] = subjectAnn$AGE[which(subjectAnn$SUBJID == sampleAnnSub$SubjectID[i])]
}

ages = as.factor(ages)

sampleAnnSub$Age = ages

gtexMatrix = gtexMatrix[,-which(ages == "20-29")]
sampleAnnSub = sampleAnnSub[-which(ages == "20-29"),]


dge = DGEList(counts = gtexMatrix)
#filter genes
keep = filterByExpr(dge)
dge = dge[keep, , keep.lib.sizes = FALSE]

dge = calcNormFactors(dge)

#add tissue
ages = vector(mode = "character", nrow(sampleAnnSub))
for(i in seq(nrow(sampleAnnSub))) {
  ages[i] = subjectAnn$AGE[which(subjectAnn$SUBJID == sampleAnnSub$SubjectID[i])]
}

ages = as.factor(ages)

sampleAnnSub$Age = ages

#set ages to mean for group
sampleAnnSub$meanAge = NA
sampleAnnSub$meanAge[which(sampleAnnSub$Age == "30-39")] = 35
sampleAnnSub$meanAge[which(sampleAnnSub$Age == "40-49")] = 45
sampleAnnSub$meanAge[which(sampleAnnSub$Age == "50-59")] = 55
sampleAnnSub$meanAge[which(sampleAnnSub$Age == "60-69")] = 65
sampleAnnSub$meanAge[which(sampleAnnSub$Age == "70-79")] = 75

mm = model.matrix(~sampleAnnSub$meanAge + sampleAnnSub$SMTS)

y = voom(dge, mm, plot = T)

fit = lmFit(y, mm)

tmp = contrasts.fit(fit, coef = 2) 
tmp = eBayes(tmp)
top.table = topTable(tmp, sort.by = "P", n = Inf)
head(top.table, 20)

rownames(top.table) = unlist(lapply(rownames(top.table), function(x){
  stringr::str_split(x, stringr::coll("."))[[1]][1]
}))

GTexDE = top.table
```


```{r}
#save
saveRDS(TCGADE, "Data/ageDEGenesCTAdj.rds")
saveRDS(TCGADETMBAdj, "Data/ageDEGenesCTAdjTMBAdj.rds")
saveRDS(GTexDE, "Data/ageDEGenesTAdjGTex.rds")

library(org.Hs.eg.db)
symbols <- mapIds(org.Hs.eg.db, keys=rownames(GTexDE), column="SYMBOL", keytype="ENSEMBL", multiVals="first")

symbols = cbind(symbols, rownames(GTexDE))

sum(is.na(symbols[,1]))
symbols2 = symbols[-which(is.na(symbols[,1])),]
sum(duplicated(symbols2[,1]))
symbols2[,1][duplicated(symbols2[,1])]
#remove duplicates
symbols3 = symbols2[-which(duplicated(symbols2[,1])),]


GTExDESub = GTexDE[which(rownames(GTexDE) %in% symbols3[,2]),]
rownames(GTExDESub) = symbols3[,1]

symbols <- mapIds(org.Hs.eg.db, keys=rownames(TCGADE), column="SYMBOL", keytype="ENSEMBL", multiVals="first")

symbols = cbind(symbols, rownames(TCGADE))

sum(is.na(symbols[,1]))
symbols2 = symbols[-which(is.na(symbols[,1])),]
sum(duplicated(symbols2[,1]))
symbols2[,1][duplicated(symbols2[,1])]
#remove duplicates
symbols3 = symbols2[-which(duplicated(symbols2[,1])),]

TCGADESub = TCGADE[which(rownames(TCGADE) %in% symbols3[,2]),]
rownames(TCGADESub) = symbols3[,1]


symbols <- mapIds(org.Hs.eg.db, keys=rownames(TCGADETMBAdj), column="SYMBOL", keytype="ENSEMBL", multiVals="first")

symbols = cbind(symbols, rownames(TCGADETMBAdj))

sum(is.na(symbols[,1]))
symbols2 = symbols[-which(is.na(symbols[,1])),]
sum(duplicated(symbols2[,1]))
symbols2[,1][duplicated(symbols2[,1])]
#remove duplicates
symbols3 = symbols2[-which(duplicated(symbols2[,1])),]

TCGADETMBSub = TCGADETMBAdj[which(rownames(TCGADETMBAdj) %in% symbols3[,2]),]
rownames(TCGADETMBSub) = symbols3[,1]

#ICB genes
TCGADESub[which(rownames(TCGADESub) %in% c("PDCD1", "CD274", "CTLA4", "CD80", "CD86")),]

TCGADETMBSub[which(rownames(TCGADETMBSub) %in% c("PDCD1", "CD274", "CTLA4", "CD80", "CD86")),]

GTExDESub[which(rownames(GTExDESub) %in% c("PDCD1", "CD274", "CTLA4", "CD80", "CD86")),]


#T exhaustion genes
GTExDESub[which(rownames(GTExDESub) %in% c("EOMES", "LAG3", "HAVCR2")),]

TCGADESub[which(rownames(TCGADESub) %in% c("EOMES", "LAG3", "HAVCR2")),]

TCGADETMBSub[which(rownames(TCGADETMBSub) %in% c("EOMES", "LAG3", "HAVCR2")),]


```

GSEA
```{r}
runFGSEA <- function(pathways, geneStats) {
  #rank based GSEA
  pathways[,1] = as.factor(pathways[,1])
  pathwayNames = levels(pathways[,1])
  
  #convert downloaded data frame to list for use with GeneOverlap package
  pathgene_list = vector(mode = "list", length = length(pathwayNames))
  for(i in seq_along(pathwayNames)){
    tmpgene_list = pathways[which(pathways[,1]==pathwayNames[i]), 2]
    pathgene_list[[i]] = tmpgene_list
  }
  names(pathgene_list) = pathwayNames
  
  pathways = pathgene_list
  
  fgsea = fgsea::fgsea(pathways, geneStats, nperm = 50000)
  fgsea = fgsea[order(fgsea$padj)]
  return(fgsea)
}

library(dplyr)
gPathways =  msigdbr::msigdbr(species = "Homo sapiens", category ="C5") %>% dplyr::select(gs_name, gene_symbol) %>% as.data.frame()

GTExStats = GTExDESub$t
names(GTExStats) = rownames(GTExDESub)

GTEXGSEAGO = runFGSEA(gPathways, GTExStats)

pathways = gPathways
pathways[,1] = as.factor(pathways[,1])
pathwayNames = levels(pathways[,1])

#convert downloaded data frame to list for use with GeneOverlap package
pathgene_list = vector(mode = "list", length = length(pathwayNames))
for(i in seq_along(pathwayNames)){
  tmpgene_list = pathways[which(pathways[,1]==pathwayNames[i]), 2]
  pathgene_list[[i]] = tmpgene_list
}
names(pathgene_list) = pathwayNames

pathways = pathgene_list


TCGAStats = TCGADESub$t
names(TCGAStats) = rownames(TCGADESub)

TCGAGSEAGO = runFGSEA(gPathways, TCGAStats)


PathwaysUpTCGA <- TCGAGSEAGO[ES > 0][which(padj < 0.05), ]
PathwaysDownTCGA <- TCGAGSEAGO[ES < 0][which(padj < 0.05), ]
PathwaysUpGTEx <- GTEXGSEAGO[ES > 0][which(padj < 0.05), ]
PathwaysDownGTEx <- GTEXGSEAGO[ES < 0][which(padj < 0.05), ]


PUpTCGAUpGTEx = PathwaysUpTCGA[PathwaysUpTCGA$pathway %in% PathwaysUpGTEx$pathway,]
PUpGTExUpTCGA = PathwaysUpGTEx[PathwaysUpGTEx$pathway %in% PathwaysUpTCGA$pathway,]

write.csv(PUpTCGAUpGTEx[,1:7], "Data/PathwaysUpTCGAUpGTEx.csv")

PUpTCGADnNsGTEx = PathwaysUpTCGA[-c(which(PathwaysUpTCGA$pathway %in% PathwaysUpGTEx$pathway)),] 
PDnNsGTExUpTCGA = GTEXGSEAGO[which(GTEXGSEAGO$pathway %in% PUpTCGADnNsGTEx$pathway),] 

write.csv(PUpTCGADnNsGTEx[,1:7], "Data/PathwaysUpTCGADnNsGTEx.csv")

PUpGTExDnNsTCGA = PathwaysUpGTEx[-c(which(PathwaysUpGTEx$pathway %in% PathwaysUpTCGA$pathway)),] 
PDnNsTCGAUpGTEx = TCGAGSEAGO[which(TCGAGSEAGO$pathway %in% PUpGTExDnNsTCGA$pathway),] 

write.csv(PDnNsTCGAUpGTEx[,1:7], "Data/PathwaysDnNsTCGAUpGTEx.csv")

PDnTCGADnGTEx = PathwaysDownTCGA[PathwaysDownTCGA$pathway %in% PathwaysDownGTEx$pathway,] 
PDnGTExDnTCGA = PathwaysDownGTEx[PathwaysDownGTEx$pathway %in% PathwaysDownTCGA$pathway,]

write.csv(PDnTCGADnGTEx[,1:7], "Data/PathwaysDnTCGADnGTEx.csv")

barplotCompare = function(Pathways1, Pathways2, nPaths, P1Name, P2Name) {
  Pathways1 = Pathways1[order(Pathways1$pval),]
  Pathways2 = Pathways2[order(Pathways2$pval),]
  
  P1ToPlot = Pathways1[1:nPaths,]
  P1Paths = P1ToPlot$pathway
  
  
  P2ToPlot = Pathways2[which(Pathways2$pathway %in% P1Paths),]
  P2Paths = P2ToPlot$pathway
  
  
  toPlot = as.data.frame(matrix(nrow = 2*nPaths, ncol = 4))
  j = 1
  for(i in seq(1, nrow(toPlot), 2)){
    toPlot[i,] = P1ToPlot[j,1:4]
    toPlot[i+1,] = P2ToPlot[which(P2Paths == P1Paths[j]),1:4]
    j =j+1
  }
  
  colnames(toPlot) = colnames(P1ToPlot)[1:4]
  
  toPlot$db = NA
  toPlot$db[seq(1, nrow(toPlot), 2)] = P1Name
  toPlot$db[seq(2, nrow(toPlot), 2)] = P2Name
  
  colorPal = grDevices::colorRampPalette(c("brown1", 
          "darkorchid1","dodgerblue"))
  
    p <- ggplot(data = toPlot, mapping = aes_string(x = as.factor(toPlot$db), y = as.factor(toPlot$pathway))) + geom_point(mapping = aes_string(size = toPlot$ES, color = toPlot$padj)) + scale_radius(range = c(2, 10)) + scale_colour_gradientn(colors = colorPal(10)) + 
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(colour = "Adj. P-Value", size = "Effect Size")
    
    print(p)
}

barplotCompare(PUpTCGAUpGTEx, PUpGTExUpTCGA, 6, "TCGA", "GTEx")
barplotCompare(PDnNsGTExUpTCGA, PUpTCGADnNsGTEx, 6, "GTEx", "TCGA")
barplotCompare(PDnNsTCGAUpGTEx, PUpGTExDnNsTCGA, 6, "TCGA", "GTEx")
barplotCompare(PDnGTExDnTCGA, PDnTCGADnGTEx, 6, "GTEx", "TCGA")
```



TCGA DE for each cancer type
```{r}
d = DGEList(counts2)

#filter low expressed genes
keep = filterByExpr(d)
d = d[keep, , keep.lib.sizes = FALSE]

d = calcNormFactors(d)

#sort phenotype information to make age groups
PhenoFilt = pheno[which(pheno$`Sample ID` %in% colnames(counts2)),]
PhenoSorted = PhenoFilt[match(colnames(counts2), PhenoFilt$`Sample ID`),]

#remove observations without age data
d1 = d[, -which(is.na(PhenoSorted$`Diagnosis Age`))]
PhenoSorted = PhenoSorted[-which(is.na(PhenoSorted$`Diagnosis Age`)),]

dCancerTypeList = vector("list", length(levels(as.factor(PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym`))))
for(i in seq_along(dCancerTypeList)){
  dCancerTypeList[[i]] = d1[, which(PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym` == levels(as.factor(PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym`))[i]), keep.lib.sizes = FALSE]
}

PhenoCT = split(PhenoSorted, PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym`)


DEREsultsList = vector("list", length(dCancerTypeList))

for(i in seq_along(dCancerTypeList)){
  mm = model.matrix(~PhenoCT[[i]]$`Diagnosis Age`)

  y = voom(dCancerTypeList[[i]], mm, plot = F)
  
  fit = lmFit(y, mm)
  
  tmp = contrasts.fit(fit, coef = 2) 
  tmp = eBayes(tmp)
  top.table = topTable(tmp, sort.by = "P", n = Inf)
  
  symbols = mapIds(org.Hs.eg.db, keys=rownames(top.table), column="SYMBOL", keytype="ENSEMBL", multiVals="first")
  
  symbols = cbind(symbols, rownames(top.table))
  
  sum(is.na(symbols[,1]))
  symbols2 = symbols[-which(is.na(symbols[,1])),]
  sum(duplicated(symbols2[,1]))
  symbols2[,1][duplicated(symbols2[,1])]
  #remove duplicates
  symbols3 = symbols2[-which(duplicated(symbols2[,1])),]
  
  top.tableSub = top.table[which(rownames(top.table) %in% symbols3[,2]),]
  rownames(top.tableSub) = symbols3[,1]
  
  DEREsultsList[[i]] = top.tableSub
}

names(DEREsultsList) = levels(as.factor(PhenoSorted$`TCGA PanCanAtlas Cancer Type Acronym`))

#remove cancers with less than 100 samples
DEREsultsList = DEREsultsList[-which(lapply(PhenoCT, nrow) < 100)]

#get T cell gene stats
TcellGenes = c("PDCD1", "CD274", "CTLA4", "CD80", "CD86")

TcellGenesStatsList = lapply(DEREsultsList, function(x){
  tmpStats = as.data.frame(matrix(nrow = length(TcellGenes), ncol = ncol(x)))
  for(i in seq_along(TcellGenes)){
    if(length(which(rownames(x) == TcellGenes[i])) == 0){
      next
    }
    else{
      tmpStats[i,] = x[which(rownames(x) == TcellGenes[i]),]
    }
  }
  return(tmpStats)
})

TcellGenesTStats = do.call(cbind, lapply(TcellGenesStatsList, function(x){x[,3]}))
rownames(TcellGenesTStats) = TcellGenes

my_palette = colorRampPalette(c("blue", "white", "darkgreen"))(n = 299)
gplots::heatmap.2(TcellGenesTStats, density.info="none", trace="none", dendrogram='both', Rowv=T, Colv=T, margins =c(6,12), col = my_palette)

```
