---
title: "GTExMIXTUREFinal"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# download GTEx version 8 at https://gtexportal.org/home/datasets ***
# gtex = phantasus::read.gct(gzfile("Data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz"))

#read in phenotype data
subjectAnn = data.table::fread("Data/phs000424.v8.pht002742.v8.p2.c1.GTEx_Subject_Phenotypes.GRU.txt")
colnames(subjectAnn) = unlist(subjectAnn[1,])
subjectAnn = subjectAnn[-1,]
subjectAnn$AGE = as.numeric(subjectAnn$AGE)

summary(subjectAnn$AGE)


sampleAnn = data.table::fread("Data/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
sampleAnnSub = sampleAnn[, c(1,6,7)]

summary(as.factor(sampleAnn$SMAFRZE))
sampleAnnSub = sampleAnnSub[which(sampleAnn$SMAFRZE == "RNASEQ"),]
summary(as.factor(sampleAnnSub$SMTS))


#format and normalize RNA-seq data
#check row and column names
library(SummarizedExperiment)
gtexMatrix = exprs(gtex)
colnames(gtexMatrix)[c(1, 45, 6000, 14444, 17382)]
rownames(gtexMatrix)[1:5]


library(edgeR)
dge = DGEList(counts = gtexMatrix)
#filter genes
keep = filterByExpr(dge)
dge = dge[keep, , keep.lib.sizes = FALSE]
dim(dge$counts)
#normalize
cpm = cpm(dge)

#convert ENSG IDs to HGNC gene symbols for use with LM22 signature gene matrix
library(org.Hs.eg.db) 

#ENSG ids contain version number; need to remove for matching
gtexGenes = rownames(cpm)
gtexGenes = unlist(lapply(gtexGenes, function(x) {stringr::str_split(x, stringr::coll("."))[[1]][1]}))

symbols <- mapIds(org.Hs.eg.db, keys=gtexGenes, column="SYMBOL", keytype="ENSEMBL", multiVals="first")

symbols = cbind(symbols, gtexGenes)

sum(is.na(symbols[,1]))
symbols2 = symbols[-which(is.na(symbols[,1])),]
sum(duplicated(symbols2[,1]))
symbols2[,1][duplicated(symbols2[,1])]

#read in lm22 signature expression matrix for immune cell types
lm22 = as.data.frame(data.table::fread("Data/LM22.txt"))
rownames(lm22) = unlist(lm22[,1])
lm22 = lm22[,-1]

#are any duplicate genes in the genes used by lm22?
sum(symbols2[,1][duplicated(symbols2[,1])] %in% rownames(lm22))
dupsym = symbols2[,1][duplicated(symbols2[,1])][symbols2[,1][duplicated(symbols2[,1])] %in% rownames(lm22)] 
#look specifically at HLA-DQA1
symbols2[,1][symbols2[,1] == dupsym] #the two are subunits of MHCII, ENSG00000237541 is called HLA-DQA2 by ENSG
sum(rownames(lm22) == "HLA-DQA2") # that one is not in lm22, so will remove 

#remove duplicates
symbols3 = symbols2[-which(duplicated(symbols2[,1])),]

#subset to genes with HGNC symbol correspondence, so that this data can be used with lm22 file
gtexCountsSym = cpm[which(gtexGenes %in% symbols3[,2]),]

symbolList = symbols3[,1]
names(symbolList) = NULL
#add symbol names
rownames(gtexCountsSym) = symbolList
```

Run MIXTURE
```{r}
source("MIXTURE/MIXTURE.R")

mixResult = MIXTURE(gtexCountsSym, lm22, iter = 500, functionMixture = nu.svm.robust.RFE, useCores = 1, nullDist = "PopulationBased")
saveRDS(mixResult, "Data/mixtureResultGTEX.rds")

absMix = (mixResult$Subjects)$MIXabs

#there are different length IDs so the subjIDs have to be specified by "-" split rather than string length
subjIDs = unlist(lapply(rownames(absMix), function(x) {
  strPieces = stringr::str_split(x,"-")[[1]][c(1,2)]
  stringr::str_c(strPieces[1], strPieces[2], sep = "-")}))
absMix = data.frame(absMix)
absMix$SubjectID = subjIDs

#filter by significant deconvolution of cell types
pvals = mixResult$p.values

rpFiltAbsMix = absMix[which(pvals[,4] < 0.05),]

#remove NA observations
nainds = which(is.na(rpFiltAbsMix[,1]))
mixtureFiltered = rpFiltAbsMix[-nainds,]

sum(is.na(mixtureFiltered))

#add age
ages = vector(mode = "character", length = nrow(mixtureFiltered))
for(i in seq(nrow(mixtureFiltered))) {
  ages[i] = subjectAnn$AGE[which(subjectAnn$SUBJID == mixtureFiltered$SubjectID[i])]
}

mixtureFiltered$Age = as.numeric(ages)
summary(mixtureFiltered$Age)

#add Sex
Sex = vector(mode = "character", length = nrow(mixtureFiltered))
for(i in seq(nrow(mixtureFiltered))) {
  Sex[i] = subjectAnn$SEX[which(subjectAnn$SUBJID == mixtureFiltered$SubjectID[i])]
}

mixtureFiltered$Sex = as.factor(Sex)
summary(mixtureFiltered$Sex)

#add tissue type
tissues = vector(mode = "character", length = nrow(mixtureFiltered))
for(i in seq(nrow(mixtureFiltered))) {
  tissues[i] = sampleAnnSub$SMTS[which(sampleAnnSub$SAMPID == rownames(mixtureFiltered)[i])]
}

mixtureFiltered$Tissue = as.factor(tissues)
summary(mixtureFiltered$Tissue)

#filter to indvididuals age 30+ for comparison to TCGA samples used
mixture2 = mixtureFiltered[-which(mixtureFiltered$Age < 30),]

mixture2$AgeGroup = cut(mixture2$Age, c(29,39,49,59,69,79,90), labels = c("30-39", "40-49", "50-59", "60-69", "70-79", "80-90"))

saveRDS(mixture2, "mixtureResultsOver29WithPheno.rds")
```


Immune Cell Modeling
```{r}
##T cells##
TCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[4:10]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

TcellLm = lm(TCellProps~Age+Sex+Tissue, data = mixture2)
summary(TcellLm)

jtools::effect_plot(TcellLm, pred = Age, interval = T, plot.points = T)


#save info for table
write.csv(summary(TcellLm)$coefficients, "~/Fertig Lab/csv/GTExTcellLM.csv")

#plot by age group
library(ggplot2)
dfboxT = data.frame(age = mixture2$AgeGroup, TCells = TCellProps)

ggplot(data = dfboxT, aes(x = age, y = TCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")
  

##Macrophages
MacrCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[14:16]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

MacrophageLm = lm(MacrCellProps~Age+Sex+Tissue, data = mixture2)
summary(MacrophageLm)

jtools::effect_plot(MacrophageLm, pred = Age, interval = T, plot.points = T)


#save info for table
write.csv(summary(MacrophageLm)$coefficients, "~/Fertig Lab/csv/GTExMacrophageLM.csv")

#plot by age group
dfboxMacr = data.frame(age = mixture2$AgeGroup, Macrophages = MacrCellProps)

ggplot(data = dfboxMacr, aes(x = age, y = Macrophages, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")

##B cells
BCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[1:3]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

BcellLm = lm(BCellProps~Age+Sex+Tissue, data = mixture2)
summary(BcellLm)

jtools::effect_plot(BcellLm, pred = Age, interval = T, plot.points = T)

ggplot(mixture2, aes(x = Age, y = BCellProps)) +
    geom_point()+
  ylab("B Cell Proportion")

#save info for table
write.csv(summary(BcellLm)$coefficients, "~/Fertig Lab/csv/GTExBcellLM.csv")

#plot by age group
dfboxB = data.frame(age = mixture2$AgeGroup, Bcells = BCellProps)

ggplot(data = dfboxB, aes(x = age, y = Bcells, fill = age)) +
  geom_boxplot() +
  theme_minimal()+
  scale_fill_brewer(palette="Blues") +
  theme(legend.position = "none")

##NK cells
NKCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[11:12]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

NKcellLm = lm(NKCellProps~Age+Sex+Tissue, data = mixture2)
summary(NKcellLm)

jtools::effect_plot(NKcellLm, pred = Age, interval = T, plot.points = T)

#save info for table
write.csv(summary(NKcellLm)$coefficients, "~/Fertig Lab/csv/GTExNKcellLM.csv")

#plot by age group
dfboxNK = data.frame(age = mixture2$AgeGroup, NKcells = NKCellProps)

ggplot(data = dfboxNK, aes(x = age, y = NKcells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.05) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")

##Dendritic cells
DCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[17:18]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

DcellLm = lm(DCellProps~Age+Sex+Tissue, data = mixture2)
summary(DcellLm)

jtools::effect_plot(DcellLm, pred = Age, interval = T, plot.points = T)

ggplot(mixture2, aes(x = Age, y = DCellProps)) +
    geom_point()+
  ylab("Dendritic Cell Proportion")

#save info for table
write.csv(summary(DcellLm)$coefficients, "~/Fertig Lab/csv/GTExDendriticcellLM.csv")

#plot by age group
dfboxD = data.frame(age = mixture2$AgeGroup, Dcells = DCellProps)

ggplot(data = dfboxD, aes(x = age, y = Dcells, fill = age)) +
  geom_boxplot() +
  theme_minimal()+
  scale_fill_brewer(palette="Blues")+
  theme(legend.position = "none")

##Misc. Myeloid
MMCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[c(13,19:22)]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[1:22]))})

MMcellLm = lm(MMCellProps~Age+Sex+Tissue, data = mixture2)
summary(MMcellLm)

jtools::effect_plot(MMcellLm, pred = Age, interval = T, plot.points = T)

#save info for table
write.csv(summary(MMcellLm)$coefficients, "~/Fertig Lab/csv/GTExMiscMyeloidLM.csv")

#plot by age group
dfboxMM = data.frame(age = mixture2$AgeGroup, MMcells = MMCellProps)

ggplot(data = dfboxMM, aes(x = age, y = MMcells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")

##summary stats
LmList = list(TcellLm, MacrophageLm, BcellLm, NKcellLm, DcellLm, MMcellLm)

ageStats = lapply(LmList, function(x){
  summary(x)$coefficients[2,]
})

names(ageStats) = c("T cells", "Macrophages", "B cells", "NK cells", "Dendritic cells", "Misc. Myeloid")

ageStatsDf = do.call(rbind, ageStats)

#adjusted pvals
p.adjust(ageStatsDf[,4], "BH")

ageStatsDf = cbind(ageStatsDf, p.adjust(ageStatsDf[,4], "BH"))
colnames(ageStatsDf)[5] = "PAdj"

write.csv(ageStatsDf, "~/Fertig Lab/csv/HOICsByAgeGTEx.csv")


ageStatsDf = as.data.frame(ageStatsDf)


ggplot(ageStatsDf, aes(x=reorder(rownames(ageStatsDf), -`t value`), y=`t value`, fill = reorder(rownames(ageStatsDf), -`t value`)))+
    geom_bar(stat="identity")+
    labs(title="Age and Immune Infiltration Across GTEx Tissues", x="Cell Type", y = "T Statistic")+
    scale_fill_hue(c=50) +
    theme_minimal()+
    theme(legend.position = "none")

```


Immune Subtypes
```{r}
immune_cells = colnames(mixture2)[1:22]
mixLMSummary = data.frame(matrix(NA, 22, 5))
for(i in 1:22) {
  lmFormula = paste(immune_cells[i], "~ Age + Tissue")
  tmpLM = lm(lmFormula, data = mixture2)
  t= broom::tidy(tmpLM)
  mixLMSummary[i,] = t[2,]
}


mixLMSummary[,1] = immune_cells
colnames(mixLMSummary) = colnames(t)
bh_adjusted_sig = mixLMSummary$term[p.adjust(mixLMSummary$p.value, method = "BH") < 0.05]
bh_adjusted_sig

mixLMSummary = mixLMSummary[order(mixLMSummary$p.value),]
mixLMSummary$PAdj = p.adjust(mixLMSummary$p.value, method = "BH")

#save
write.csv(mixLMSummary, "~/Fertig Lab/csv/GTExImmuneSubtypeByAgeStats.csv")

#plot statistic
ggplot(mixLMSummary, aes(x=reorder(mixLMSummary[,1], -mixLMSummary[, 4]), y=mixLMSummary[, 4], fill = reorder(mixLMSummary[,1], -mixLMSummary[, 4])))+
    geom_bar(stat="identity")+
    labs(title="Age and Immune Infiltration GTEx Across Tissues", x="Cell Type", y = "Statistic")+
  theme_minimal()+
   scale_fill_hue(c=50) +
    theme(legend.position = "none")


```


Immune cell proportions
```{r}
##CD8/Treg

CD8TregCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[4]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[c(4,9)]))})

CD8TregcellLm = lm(CD8TregCellProps~Age+Sex+Tissue, data = mixture2)
summary(CD8TregcellLm)


#save info for table
write.csv(summary(CD8TregcellLm)$coefficients, "~/Fertig Lab/csv/GTExCD8TregcellLmLM.csv")

#plot by age group
dfboxCD8Treg = data.frame(age = mixture2$AgeGroup, CD8Treg = CD8TregCellProps)

ggplot(data = dfboxCD8Treg, aes(x = age, y = CD8Treg, fill = age)) +
  geom_boxplot() +
  theme_minimal()+
  scale_fill_brewer(palette="Blues")+
  theme(legend.position = "none")


##M1/M2

M1M2CellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[15]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[c(15,16)]))})

M1M2cellLm = lm(M1M2CellProps~Age+Sex+Tissue, data = mixture2)
summary(M1M2cellLm)


#save info for table
write.csv(summary(M1M2cellLm)$coefficients, "~/Fertig Lab/csv/GTExM1M2cellLmLM.csv")

#plot by age group
dfboxM1M2 = data.frame(age = mixture2$AgeGroup, M1M2 = M1M2CellProps)

ggplot(data = dfboxM1M2, aes(x = age, y = M1M2, fill = age)) +
  geom_boxplot() +
  theme_minimal()+
  scale_fill_brewer(palette="Blues")+
  theme(legend.position = "none")


##CD8/CD4T
CD8CD4TCellProps = apply(mixture2, 1, function(x) {sum(as.numeric(x[4]))})/apply(mixture2, 1, function(x) {sum(as.numeric(x[4:7]))})

CD8CD4TcellLm = lm(CD8CD4TCellProps~Age+Sex+Tissue, data = mixture2)
summary(CD8CD4TcellLm)


#save info for table
write.csv(summary(CD8CD4TcellLm)$coefficients, "~/Fertig Lab/csv/GTExCD8CD4TcellLmLM.csv")

#plot by age group
dfboxCD8CD4T = data.frame(age = mixture2$AgeGroup, CD8CD4T = CD8CD4TCellProps)

ggplot(data = dfboxCD8CD4T, aes(x = age, y = CD8CD4T, fill = age)) +
  geom_boxplot() +
  theme_minimal()+
  scale_fill_brewer(palette="Blues")+
  theme(legend.position = "none")


##summary stats
  propLmList = list(CD8TregcellLm, M1M2cellLm, CD8CD4TcellLm)

propAgeStats = lapply(propLmList, function(x){
  summary(x)$coefficients[2,]
})

names(propAgeStats) = c("CD8 to Treg", "M1 to M2", "CD8 to CD4")

propAgeStatsDf = do.call(rbind, propAgeStats)

#adjusted pvals
p.adjust(propAgeStatsDf[,4], "BH")

propAgeStatsDf = cbind(propAgeStatsDf, p.adjust(propAgeStatsDf[,4], "BH"))
colnames(propAgeStatsDf)[5] = "PAdj"

propAgeStatsDf

write.csv(propAgeStatsDf, "~/Fertig Lab/csv/ImmunePropsByAgeGTEx.csv")
```

