---
title: "TCGAMIXTUREAnalysisFinal"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# *** TCGA RNA-seq data are available at https://figshare.com/articles/TCGARNA-seq/12030318 
# rna_seq_data = data.table::fread("Data/all_cancers_rnaseq.txt")

rna_seq_data_2 = rna_seq_data[,-1]
#remove character columns describing each cancer type
clsList = as.factor(as.character(lapply(rna_seq_data_2, class)))
summary(clsList)
rmCols = unlist(as.numeric(c(which(clsList == "character"), which(clsList == "integer"))))
rna_seq_data_2 = rna_seq_data_2[,-c(642,1611,2152, 3061, 3946, 4831, 5681, 6496, 7345,  643, 1612, 2153, 3062, 3947, 4832, 5682, 6497, 7346, 8261)] 
rownames(rna_seq_data_2) = as.character(unlist(rna_seq_data[,1]))

#read in signature gene matrix for 22 immune cell types
lm22 = as.data.frame(data.table::fread("Data/LM22.txt"))
rownames(lm22) = unlist(lm22[,1])
lm22 = lm22[,-1]

source("MIXTURE/MIXTURE.R")
#call MIXTURE
mixResult = MIXTURE(rna_seq_data_2, lm22, iter = 500, functionMixture = nu.svm.robust.RFE, useCores = 1, nullDist = "PopulationBased")

saveRDS(mixResult, "Data/MIXTURE_result.rds")

#get absolute proportions
absMix = (mixResult$Subjects)$MIXabs 
sum(is.na(absMix))
pvals = mixResult$p.values

#filter to observations with significant deconvolution
rpFiltAbsMix = absMix[which(pvals[,4] < 0.05),]
nainds = which(is.na(rpFiltAbsMix[,1]))
mixtureFiltered = rpFiltAbsMix[-nainds,]

#remove samples that had received treatment prior to collection, as this could bias result
mixtureIDs = rownames(mixtureFiltered)

mixtureIDs = unlist(lapply(mixtureIDs, function(x){
  stringr::str_sub(x, 1, 12)
}))

treatedIDs = readRDS("Data/treatedBeforeResectionIDs.rds")
mixtureFiltered = mixtureFiltered[-which(mixtureIDs %in% treatedIDs),]

#get phenotype data
pheno = data.table::fread("Data/tcga_clinical_data.tsv")

sampleIDs = rownames(mixtureFiltered)
case_IDs = lapply(sampleIDs, stringr::str_sub, start = 1, end = 12)

rownames(mixtureFiltered) = case_IDs
mixtureFiltered = cbind(as.data.frame(mixtureFiltered), sampleIDs)

#function to add phenotype data
source("Functions/mixture_pheno_filter.R")

all_surv_usable_cancer_types = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", 
                                 "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", 
                                 "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", 
                                 "PAAD", "PRAD", "READ", "SARC", "SKCM", "STAD",                                   "THCA", "UCEC", "UCS", "UVM")

mixtureWithPheno = mixture_pheno_filter(mixtureFiltered, pheno, cancer_types = all_surv_usable_cancer_types)

#format OSS for eventual use with cox proportional hazards model
liveinds = which(mixtureWithPheno$Overall.Survival.Status == "LIVING")
deadinds = which(mixtureWithPheno$Overall.Survival.Status == "DECEASED")
mixtureWithPheno$Overall.Survival.Status = as.numeric(mixtureWithPheno$Overall.Survival.Status)
mixtureWithPheno$Overall.Survival.Status[liveinds] = 0
mixtureWithPheno$Overall.Survival.Status[deadinds] = 1

#remove samples with NA values for Age
mixtureData = mixtureWithPheno[-which(is.na(mixtureWithPheno$Diagnosis.Age)), ]


#add cancer type and smoking years
cancerType = vector("character", length(nrow(mixtureData)))
notPrimary = c()
for(i in seq(nrow(mixtureData))) {
  cancerType[i] = pheno$`TCGA PanCanAtlas Cancer Type Acronym`[which(pheno$`Sample ID` == mixtureData$Sample.ID[i])]
  if(pheno$`Sample Type`[which(pheno$`Sample ID` == mixtureData$Sample.ID[i])] != "Primary") {
    notPrimary = c(notPrimary, i)
    }
}

mixtureData$Cancer.Type = as.factor(cancerType)
summary(mixtureData$Cancer.Type)

#remove those that are not primary samples
mixDataSub = mixtureData[-notPrimary,]

#add smoking years
smokingData = readRDS("Data/smokingData.rds")

mixDataSub$Smoking.Years = NA
for(i in seq(nrow(mixDataSub))) {
  if(length(which(smokingData$submitter_id == mixDataSub$Patient.ID[i])) == 0){
    next
  }
 mixDataSub$Smoking.Years[i] = smokingData$years_smoked[which(smokingData$submitter_id == mixDataSub$Patient.ID[i])]
}

#add age group variable
mixDataSub$ageGroup = cut(mixDataSub$Diagnosis.Age, c(29,39,49,59,69,79,90), labels = c("30-39", "40-49", "50-59", "60-69", "70-79", "80-90"))

saveRDS(mixDataSub, "TCGA_MIXTURE_filtered.rds")
```



Test if higher order cell types are associated with age
```{r}
##T cells##
TCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[4:10]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})


TcellLm = lm(TCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(TcellLm)


#save info for table
write.csv(summary(TcellLm)$coefficients, "~/Fertig Lab/csv/TcellLM.csv")

#plot lm
jtools::effect_plot(TcellLm, pred = Diagnosis.Age, interval = T, plot.points = T, y.label = "T cell Absolute Proportion")

#plot by age group
library(ggplot2)
dfboxT = data.frame(age = mixDataSub$ageGroup, TCells = TCellProps)

ggplot(data = dfboxT, aes(x = age, y = TCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")


##Macrophages
MacrCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[14:16]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})

ggplot(mixDataSub, aes(x = Diagnosis.Age, y = MacrCellProps)) +
    geom_point()+
    ylab("Macrophage Proportion")

MacrophageLm = lm(MacrCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(MacrophageLm)

#save info for table
write.csv(summary(MacrophageLm)$coefficients, "~/Fertig Lab/csv/MacrophageLM.csv")

#plot lm
jtools::effect_plot(MacrophageLm, pred = Diagnosis.Age, interval = T, plot.points = T, y.label = "Macrophage Absolute Proportion")

#plot by age group
dfboxMacr = data.frame(age = mixDataSub$ageGroup, Macrophages = MacrCellProps)

ggplot(data = dfboxMacr, aes(x = age, y = Macrophages, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Blues") +
  theme_minimal()+
  theme(legend.position = "none")


##B cells
BCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:3]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})

ggplot(mixDataSub, aes(x = Diagnosis.Age, y = BCellProps)) +
    geom_point()+
    ylab("B Cell Proportion")

BcellLm = lm(BCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(BcellLm)


#save info for table
write.csv(summary(BcellLm)$coefficients, "~/Fertig Lab/csv/BcellLM.csv")


#plot lm
jtools::effect_plot(BcellLm, pred = Diagnosis.Age, interval = T, plot.points = T)

#plot by age group
dfboxB = data.frame(age = mixDataSub$ageGroup, BCells = BCellProps)

ggplot(data = dfboxB, aes(x = age, y = BCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Dark2") +
  theme_minimal()

##NK cells
NKCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[11:12]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})

ggplot(mixDataSub, aes(x = Diagnosis.Age, y = NKCellProps)) +
    geom_point()+
    ylab("NK Cell Proportion")

NKcellLm = lm(NKCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(NKcellLm)

#save info for table
write.csv(summary(NKcellLm)$coefficients, "~/Fertig Lab/csv/NKcellLM.csv")

#plot lm
jtools::effect_plot(NKcellLm, pred = Diagnosis.Age, interval = T, plot.points = T)

#plot by age group
dfboxNK = data.frame(age = mixDataSub$ageGroup, NKCells = NKCellProps)

ggplot(data = dfboxNK, aes(x = age, y = NKCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Dark2") +
  theme_minimal()

##Dendritic cells
DCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[17:18]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})

ggplot(mixDataSub, aes(x = Diagnosis.Age, y = DCellProps)) +
    geom_point()+
    ylab("Dendritic Cell Proportion")

DcellLm = lm(DCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(DcellLm)


#save info for table
write.csv(summary(DcellLm)$coefficients, "~/Fertig Lab/csv/DcellLM.csv")

#plot lm
jtools::effect_plot(DcellLm, pred = Diagnosis.Age, interval = T, plot.points = T)

#plot by age group
dfboxD = data.frame(age = mixDataSub$ageGroup, DCells = DCellProps)

ggplot(data = dfboxD, aes(x = age, y = DCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Dark2") +
  theme_minimal()

##Misc. Myeloid
MMCellProps = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[c(13,19:22)]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[1:22]))})

ggplot(mixDataSub, aes(x = Diagnosis.Age, y = MMCellProps)) +
    geom_point()+
    ylab("Misc. Myeloid Proportion")

MMcellLm = lm(MMCellProps~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(MMcellLm)


#save info for table
write.csv(summary(MMcellLm)$coefficients, "~/Fertig Lab/csv/MMcellLM.csv")

#plot lm
jtools::effect_plot(MMcellLm, pred = Diagnosis.Age, interval = T, plot.points = T)

#plot by age group
dfboxMM = data.frame(age = mixDataSub$ageGroup, MMCells = MMCellProps)

ggplot(data = dfboxMM, aes(x = age, y = MMCells, fill = age)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.2) +
  scale_fill_brewer(palette="Dark2") +
  theme_minimal()

##summary stats
lmList = list(TcellLm, MacrophageLm, BcellLm, NKcellLm, DcellLm, MMcellLm)

ageStats = lapply(lmList, function(x){
  summary(x)$coefficients[2,]
})

names(ageStats) = c("T cells", "Macrophages", "B cells", "NK cells", "Dendritic cells", "Misc. Myeloid")

ageStatsDf = do.call(rbind, ageStats)

#adjusted pvals
p.adjust(ageStatsDf[,4], "BH")

ageStatsDf = as.data.frame(cbind(ageStatsDf, p.adjust(ageStatsDf[,4], "BH")))
colnames(ageStatsDf)[5] = "PAdj"

write.csv(ageStatsDf, "~/Fertig Lab/csv/HOICsByAgeTCGA.csv")


ageStatsDf = as.data.frame(ageStatsDf)

#plot
ggplot(ageStatsDf, aes(x=reorder(rownames(ageStatsDf), -`t value`), y=`t value`, fill = reorder(rownames(ageStatsDf), -`t value`)))+
    geom_bar(stat="identity")+
    labs(title="Linear Relationship of Age and Immune Infiltration Pan-Cancer", x="Cell Type", y = "T Statistic")+
    scale_fill_hue(c=50) +
    theme_minimal()+
    theme(legend.position = "none")

ggplot(CCStats, aes(x=reorder(xnames, -CCstats), y=CCstats, fill = reorder(xnames, -CCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for COAD patients", x="Cell Type", y = "F Statistic")+
    theme_minimal()+
     scale_fill_hue(c=60) +
    theme(legend.position = "none")


##Cox proportional hazards model
library(survival)

Tcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ TCellProps + Sex +Diagnosis.Age +strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

Mcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ MacrCellProps+ Sex +Diagnosis.Age +strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

Bcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ BCellProps + Sex +Diagnosis.Age + strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

NKcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ NKCellProps + Sex +Diagnosis.Age + strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

Dcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ DCellProps + Sex +Diagnosis.Age + strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

MMcox = coxph(Surv(Overall.Survival..Months., Overall.Survival.Status)~ MMCellProps + Sex +Diagnosis.Age + strata(Cancer.Type) + Smoking.Years, data = mixDataSub)

#summary stats
coxList = list(Tcox, Mcox, Bcox, NKcox, Dcox, MMcox)

coxStats = lapply(coxList, function(x){
  summary(x)$coefficients[1,]
})

names(coxStats) = c("T cells", "Macrophages", "B cells", "NK cells", "Dendritic cells", "Misc. Myeloid")

coxStatsDf = do.call(rbind, coxStats)

#adjusted pvals
p.adjust(coxStatsDf[,5], "BH")

coxStatsDf = cbind(coxStatsDf, p.adjust(coxStatsDf[,5], "BH"))
colnames(coxStatsDf)[6] = "PAdj"

write.csv(coxStatsDf, "~/Fertig Lab/csv/HOICsCoxTCGA.csv")

coxStatsDf

coxStatsDf = as.data.frame(coxStatsDf)

ggplot(coxStatsDf, aes(x=reorder(rownames(coxStatsDf), -z), y=z))+
    geom_bar(stat="identity")+
    labs(title="Cox Statistic for Immune Infiltration Pan-Cancer", x="Cell Type", y = "Z-Statistic")+
    theme_classic()


```

Look for associations with age among immune cell subtypes
```{r}
#iterate through the 22 immune cell types and fit linear model for each to age
immune_cells = colnames(mixDataSub)[1:22]
mixLMSummary = data.frame(matrix(NA, 22, 5))
for(i in 1:22) {
  lmFormula = paste(immune_cells[i], "~ Diagnosis.Age + Sex + Cancer.Type")
  tmpLM = lm(lmFormula, data = mixDataSub)
  t= broom::tidy(tmpLM)
  mixLMSummary[i,] = t[2,]
}


mixLMSummary[,1] = immune_cells
colnames(mixLMSummary) = colnames(t)
bh_adjusted_sig = mixLMSummary$term[p.adjust(mixLMSummary$p.value, method = "BH") < 0.05]
bh_adjusted_sig

mixLMSummary = mixLMSummary[order(mixLMSummary$p.value),]
mixLMSummary$PAdj = p.adjust(mixLMSummary$p.value, method = "BH")

#save
write.csv(mixLMSummary, "~/Fertig Lab/csv/ImmuneSubtypeByAgeStats.csv")

#plot statistic
ggplot(mixLMSummary, aes(x=reorder(mixLMSummary[,1], -mixLMSummary[, 4]), y=mixLMSummary[, 4]))+
    geom_bar(stat="identity")+
    labs(title="Linear Relationship of Age and Immune Infiltration Pan-Cancer", x="Cell Type", y = "Statistic")+
    theme_classic()


##cox hazards
source('Functions/coxph_model_mixture.R')
cox = coxph_model_mixture(mixDataSub, time = "Overall.Survival..Months.", event = "Overall.Survival.Status", covars = "Sex + Diagnosis.Age + strata(Cancer.Type) + Smoking.Years")

cox

#save
write.csv(cox$`Ordered Cell Types`, "~/Fertig Lab/csv/CoxSubtypesTCGA.csv")

#plot
#plot statistic
ggplot(cox$`Ordered Cell Types`, aes(x=reorder(cox$`Ordered Cell Types`[,1], -cox$`Ordered Cell Types`[, 4]), y=cox$`Ordered Cell Types`[, 4]))+
    geom_bar(stat="identity")+
    labs(title="Cox Statistic for Immune Infiltration Pan-Cancer", x="Cell Type", y = "Z-Statistic")+
    theme_classic()

mixDataSub$logTMB = log(mixDataSub$Mutation.Count)

##add TMB
mixLMSummary = data.frame(matrix(NA, 22, 5))
for(i in 1:22) {
  lmFormula = paste(immune_cells[i], "~ Diagnosis.Age + Sex + Cancer.Type + logTMB")
  tmpLM = lm(lmFormula, data = mixDataSub)
  t= broom::tidy(tmpLM)
  mixLMSummary[i,] = t[2,]
}


mixLMSummary[,1] = immune_cells
colnames(mixLMSummary) = colnames(t)
bh_adjusted_sig = mixLMSummary$term[p.adjust(mixLMSummary$p.value, method = "BH") < 0.05]
bh_adjusted_sig

mixLMSummary = mixLMSummary[order(mixLMSummary$p.value),]
mixLMSummary$PAdj = p.adjust(mixLMSummary$p.value, method = "BH")

#save
write.csv(mixLMSummary, "~/Fertig Lab/csv/ImmuneSubtypeByAgeStatsTMBAdj.csv")
```


Investigate age association of proportions of immune cells thought to be good/bad prognostics
```{r}
##CD8T/Tregs
CD8_Tregprop = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[c(4)]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[c(4,9)]))})

CD8TregLm = lm(CD8_Tregprop~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)

summary(CD8TregLm)

jtools::effect_plot(CD8TregLm, pred = Diagnosis.Age, interval = T)

write.csv(summary(CD8TregLm)$coefficients, "~/Fertig Lab/csv/CD8TregStats.csv")

#plot by age group
means = aggregate(CD8_Tregprop~as.factor(mixDataSub$ageGroup), FUN = mean)
sds = aggregate(CD8_Tregprop~as.factor(mixDataSub$ageGroup), FUN = stats::sd)

df = data.frame(age = as.factor(means[,1]), PC = means[,2])
sd = sds[,2]

ggplot(data = df, aes(x = age, y = PC)) +
  geom_col(fill = "steelblue")+
  geom_errorbar(aes(ymin = 0, ymax = PC+sd), width = 0.2) +
  labs(title="Proportion of CD8/Tregs with age", 
         x="Age Group", y = "CD8 to Treg cell Proportion") +
  theme_minimal() +
  theme(legend.position = "none")

## M1/M2
M1_M2prop = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[15]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[c(15,16)]))})

M1M2Lm = lm(M1_M2prop~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)
summary(M1M2Lm)

jtools::effect_plot(M1M2Lm, pred = Diagnosis.Age, interval = T)


means = aggregate(M1_M2prop~as.factor(mixDataSub$ageGroup), FUN = mean)
sds = aggregate(M1_M2prop~as.factor(mixDataSub$ageGroup), FUN = stats::sd)

df = data.frame(age = as.factor(means[,1]), PC = means[,2])
sd = sds[,2]

ggplot(data = df, aes(x = age, y = PC, fill = age)) +
  geom_col()+
  geom_errorbar(aes(ymin = 0, ymax = PC+sd), width = 0.2) +
  labs(title="Proportion of M1/M2 cells with age", 
         x="Age Group", y = "M1 to M2 cell Proportion") +
  theme_minimal() +
  theme(legend.position = "none")

##CD8T/CD4T
CD8_CD4prop = apply(mixDataSub, 1, function(x) {sum(as.numeric(x[4]))})/apply(mixDataSub, 1, function(x) {sum(as.numeric(x[c(4:7)]))})

CD8CD4Lm = lm(CD8_CD4prop~Diagnosis.Age+Sex+Cancer.Type, data = mixDataSub)
summary(CD8CD4Lm)

jtools::effect_plot(CD8CD4Lm, pred = Diagnosis.Age, interval = T)

means = aggregate(CD8_CD4prop~as.factor(mixDataSub$ageGroup), FUN = mean)
sds = aggregate(CD8_CD4prop~as.factor(mixDataSub$ageGroup), FUN = stats::sd)

df = data.frame(age = as.factor(means[,1]), PC = means[,2])
sd = sds[,2]

ggplot(data = df, aes(x = age, y = PC, fill = age)) +
  geom_col()+
  geom_errorbar(aes(ymin = 0, ymax = PC+sd), width = 0.2) +
  labs(title="Proportion of CD8/CD4 cells with age", 
         x="Age Group", y = "CD8 to CD4 T cell Proportion") +
  theme_minimal() +
  theme(legend.position = "none")

##summary stats
propLmList = list(CD8TregLm, M1M2Lm, CD8CD4Lm)

propAgeStats = lapply(propLmList, function(x){
  summary(x)$coefficients[2,]
})

names(propAgeStats) = c("CD8 to Treg", "M1 to M2", "CD8 to CD4")

propAgeStatsDf = do.call(rbind, propAgeStats)

#adjusted pvals
p.adjust(propAgeStatsDf[,4], "BH")

propAgeStatsDf = cbind(propAgeStatsDf, p.adjust(propAgeStatsDf[,4], "BH"))
colnames(propAgeStatsDf)[5] = "PAdj"

propAgeStatsDf

write.csv(propAgeStatsDf, "~/Fertig Lab/csv/ImmunePropsByAgeTCGA.csv")


##cox hazards

CD8TregCox = coxph(Surv(mixDataSub$Overall.Survival..Months., mixDataSub$Overall.Survival.Status)~ CD8_Tregprop + mixDataSub$Diagnosis.Age + strata(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym) + mixDataSub$Sex + mixDataSub$Smoking.Years)

M1M2Cox = coxph(Surv(mixDataSub$Overall.Survival..Months., mixDataSub$Overall.Survival.Status)~M1_M2prop + mixDataSub$Diagnosis.Age + strata(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym) + mixDataSub$Sex + mixDataSub$Smoking.Years)

CD8CD4Cox = coxph(Surv(mixDataSub$Overall.Survival..Months., mixDataSub$Overall.Survival.Status)~CD8_CD4prop + mixDataSub$Diagnosis.Age + strata(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym) + mixDataSub$Sex + mixDataSub$Smoking.Years)

propCoxList = list(CD8TregCox, M1M2Cox, CD8CD4Cox)

propCoxStats = lapply(propCoxList, function(x){
  summary(x)$coefficients[1,]
})

names(propCoxStats) = c("CD8 to Treg", "M1 to M2", "CD8 to CD4")

propCoxStatsDf = do.call(rbind, propCoxStats)

#adjusted pvals
p.adjust(propCoxStatsDf[,5], "BH")

propCoxStatsDf = cbind(propCoxStatsDf, p.adjust(propCoxStatsDf[,5], "BH"))
colnames(propCoxStatsDf)[6] = "PAdj"

propCoxStatsDf

write.csv(propCoxStatsDf, "~/Fertig Lab/csv/ImmunePropsCoxTCGA.csv")
```


Examine age and survival association by individual cancer type
```{r}
mixtureDataNP = mixtureFiltered


cancerTypeList = c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", 
                   "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", 
                   "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", 
                   "PAAD", "PRAD", "READ", "SARC", "SKCM", "STAD", 
                   "THCA", "UCEC", "UCS", "UVM")

indvCancerDataList = list()

for(i in 1:length(cancerTypeList)){
  tmpDataFilter = mixture_pheno_filter(mixtureDataNP, pheno, cancer_types = cancerTypeList[i])
  indvCancerDataList[[i]] = tmpDataFilter
}
names(indvCancerDataList) = cancerTypeList

#how many samples in each group
dims = lapply(indvCancerDataList, dim)
nsamples = unlist(lapply(dims, function(l) l[[1]]))
nsamples

#remove groups that have less than 100 samples
indvCancerDataList2 = indvCancerDataList[which(nsamples>=100)]

#what are the age distributions of each of the cancers
lapply(indvCancerDataList2, function(x) {
  summary(x$Diagnosis.Age)
})


#format survival data
for(i in 1:length(indvCancerDataList2)){
liveinds = which(indvCancerDataList2[[i]]$Overall.Survival.Status == "LIVING")
deadinds = which(indvCancerDataList2[[i]]$Overall.Survival.Status == "DECEASED")
indvCancerDataList2[[i]]$Overall.Survival.Status = as.numeric(indvCancerDataList2[[i]]$Overall.Survival.Status)
indvCancerDataList2[[i]]$Overall.Survival.Status[liveinds] = 0
indvCancerDataList2[[i]]$Overall.Survival.Status[deadinds] = 1
}


#create higher order cell types then run lm
runLmAgeImmune = function(mixtureData){
  mixtureData$Bcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:3]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Tcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[4:10]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$NKcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[11:12]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$MiscMyeloid = apply(mixtureData, 1, function(x) {sum(as.numeric(x[c(13,19:22)]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Macrophages = apply(mixtureData, 1, function(x) {sum(as.numeric(x[14:16]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Dendriticcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[17:18]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixLMSummary = data.frame(matrix(NA, 6, 5))
  colnames(mixLMSummary) = c("Immune.Cell", "estimate", "std.error", "statistic", "p.value")
  celltypes = colnames(mixtureData[c("Bcells", "Tcells", "NKcells", "MiscMyeloid", "Macrophages", "Dendriticcells")])
for(i in 1:6) {
  lmFormula = paste(celltypes[i], "~ Diagnosis.Age")
  tmpLM = lm(lmFormula, data = mixtureData)
  t= broom::tidy(tmpLM)
  mixLMSummary[i,] = t[2,]
  mixLMSummary[i,1] = celltypes[i]
}
  return(mixLMSummary)
}

byCancerLMs = lapply(indvCancerDataList2, runLmAgeImmune)

byCancerLMs = lapply(byCancerLMs, function(x){
  x$p.adj = p.adjust(x$p.value, "BH")
  return(x)
})

saveRDS(byCancerLMs, "TCGAAgeImmuneLM_CT.rds")

#save
for(i in seq_along(byCancerLMs)){
  fileName = paste("~/Fertig Lab/csv/", names(byCancerLMs)[i], "cancerAgeLMStats.csv", sep = "")
  write.csv(byCancerLMs[[i]], fileName)
}

#remove sarc
byCancerLMs = byCancerLMs[-which(names(byCancerLMs) == "SARC")]

lmPvals = lapply(byCancerLMs, function(x){x[,5]})
lmPvalMatrix = matrix(unlist(lmPvals), nrow = length(lmPvals[[1]]))
logPvalMatrix = -log10(lmPvalMatrix)

colnames(logPvalMatrix) = names(byCancerLMs)
rownames(logPvalMatrix) = c("B cells", "T cells", "NK cells", "Misc. Myeloid", "Macrophages", "Dendritic Cells")

#heatmap
library(gplots)
library(RColorBrewer)
colors <- c(min(logPvalMatrix),seq(2,max(logPvalMatrix),by=0.1))

my_palette = c("blue", colorRampPalette(c("lightgreen", "darkgreen"))(n = length(colors)-2))
gplots::heatmap.2(logPvalMatrix, density.info="none", trace="none", dendrogram='both', Rowv=T, Colv=T, margins =c(6,12), col = my_palette, breaks = colors)


#lm effect
lmEffect = lapply(byCancerLMs, function(x){x[,2]})
lmEffectsMatrix = matrix(unlist(lmEffect), nrow = length(lmEffect[[1]]))
lmEffectsMatrix[which(is.na(lmEffectsMatrix))] = 0

colnames(lmEffectsMatrix) = names(byCancerLMs)
rownames(lmEffectsMatrix) = c("B cells", "T cells", "NK cells", "Misc. Myeloid", "Macrophages", "Dendritic Cells")

lmPvals = lapply(byCancerLMs, function(x){x[,6]})
lmPvalMatrix = matrix(unlist(lmPvals), nrow = length(lmPvals[[1]]))
lmPvalMatrix[which(lmPvalMatrix < 0.05)] = "*"
lmPvalMatrix[which(lmPvalMatrix >= 0.05)] = ""


#heatmap
my_palette = colorRampPalette(c("blue", "white", "darkgreen"))(n = 299)
heatmap.2(lmEffectsMatrix, density.info="none", trace="none", dendrogram='both', Rowv=T, Colv=T, margins =c(6,12), col=my_palette, cellnote = lmPvalMatrix, notecol = "black", notecex = 2.0)

##cox model

higherOrderImmuneTypes = function(mixtureData){
  mixtureData$Bcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:3]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Tcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[4:10]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$NKcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[11:12]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$MiscMyeloid = apply(mixtureData, 1, function(x) {sum(as.numeric(x[c(13,19:22)]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Macrophages = apply(mixtureData, 1, function(x) {sum(as.numeric(x[14:16]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  mixtureData$Dendriticcells = apply(mixtureData, 1, function(x) {sum(as.numeric(x[17:18]))})/apply(mixtureData, 1, function(x) {sum(as.numeric(x[1:22]))})
  return(mixtureData)
}

higherOrder = lapply(indvCancerDataList2, higherOrderImmuneTypes)

indvCancerProgs = lapply(higherOrder, coxph_model_mixture, time = "Overall.Survival..Months.", event = "Overall.Survival.Status", covars = "Diagnosis.Age", startcolumn = 45, endcolumn = 50)

#save
for(i in seq_along(indvCancerProgs)){
  fileName = paste("~/Fertig Lab/csv/", names(indvCancerProgs)[i], "cancerImmuneCoxStats.csv", sep = "")
  write.csv(indvCancerProgs[[i]]$`Ordered Cell Types`, fileName)
}

#order so all immune cells match and get statistics for each cancer type
progStats = lapply(indvCancerProgs, function(x) {x[[3]][order(x[[3]][,1]),]$statistic})
pS = as.data.frame(progStats)
#cell types in order 
pS = as.matrix(pS)
rownames(pS) = indvCancerProgs[[1]][[3]][,1][order(indvCancerProgs[[1]][[3]][,1])]
rownames(pS)
rownames(pS) = c("B cells", "Dendritic cells", "Macrophages", "Misc. Myeloid", "NK cells", "T cells")

my_palette = colorRampPalette(c("blue", "white", "red"))(n = 299)
heatmap.2(pS, density.info="none", trace="none", dendrogram='both', Rowv=T, Colv=T, margins =c(6,12), col=my_palette)

#hazard ratio heatmap
progStats = lapply(indvCancerProgs, function(x) {x[[3]][order(x[[3]][,1]),]$estimate})
pS = as.data.frame(progStats)
#cell types in order 
pS = as.matrix(pS)
rownames(pS) = indvCancerProgs[[1]][[3]][,1][order(indvCancerProgs[[1]][[3]][,1])]
rownames(pS)
rownames(pS) = c("B cells", "Dendritic cells", "Macrophages", "Misc. Myeloid", "NK cells", "T cells")

my_palette = colorRampPalette(c("blue", "white", "red"))(n = 299)
heatmap.2(pS, density.info="none", trace="none", dendrogram='both', Rowv=T, Colv=T, margins =c(6,12), col=my_palette)
```



Compare tissue cancer immune changes with gtex tissue immune changes
```{r}
##Lung

lungCancer = mixDataSub[which(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym == "LUSC" | mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym == "LUAD") ,]

Gtex = readRDS("Data/mixtureResultsOver29WithPheno.rds")
summary(Gtex$Tissue)

lungGtex = Gtex[which(Gtex$Tissue == "Lung"),]

outLC = higherOrderImmuneTypes(lungCancer)
outL = higherOrderImmuneTypes(lungGtex)

higherOrderIC = c("Bcells", "Tcells", "NKcells", "MiscMyeloid", "Macrophages", "Dendriticcells")

lmListLC = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Diagnosis.Age"))
  lm = lm(formula, outLC)
  lmListLC[[i]] = lm
}

LCdat = lapply(lmListLC, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(LCdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(LCdat) = higherOrderIC
LCdf = do.call(rbind, LCdat)
LCdf = as.data.frame(LCdf)
LCdf$PAdj = p.adjust(LCdf[,4], "BH")
LCdf

#save
write.csv(LCdf, "~/Fertig Lab/csv/LungCancerImmuneAge.csv")

lmListL = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Age"))
  lm = lm(formula, outL)
  lmListL[[i]] = lm
}

Ldat = lapply(lmListL, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(Ldat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(Ldat) = higherOrderIC
Ldf = do.call(rbind, Ldat)
Ldf = as.data.frame(Ldf)
Ldf$PAdj = p.adjust(Ldf[,4], "BH")
Ldf
#save
write.csv(Ldf, "~/Fertig Lab/csv/LungImmuneAge.csv")

#plot
LCstats = unlist(lapply(LCdat, function(x){x[3]}))
Lstats = unlist(lapply(Ldat, function(x){x[3]}))

names(LCstats) = higherOrderIC
names(Lstats) = higherOrderIC

xnames = c("B cells", "T cells", "NK cells", "Misc. Myeloid", "Macrophages", "Dendritic cells")

LCStats = as.data.frame(LCstats)

ggplot(LCStats, aes(x=reorder(xnames, -LCstats), y=LCstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for Lung cancer patients", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
     scale_fill_hue(c=60) +
    theme(legend.position = "none")

LStats = as.data.frame(Lstats)

ggplot(LStats, aes(x=reorder(xnames, -Lstats), y=Lstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for GTEx lung Samples", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
   scale_fill_hue(c=60) +
    theme(legend.position = "none")

## Breast

breastCancer = mixDataSub[which(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym == "BRCA") ,]

breastGtex = Gtex[which(Gtex$Tissue == "Breast"),]

outBC = higherOrderImmuneTypes(breastCancer)
outB = higherOrderImmuneTypes(breastGtex)

lmListBC = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Diagnosis.Age"))
  lm = lm(formula, outBC)
  lmListBC[[i]] = lm
}

BCdat = lapply(lmListBC, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(BCdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(BCdat) = higherOrderIC
BCdf = do.call(rbind, BCdat)
BCdf = as.data.frame(BCdf)
BCdf$PAdj = p.adjust(BCdf[,4], "BH")
BCdf

#save
write.csv(BCdf, "~/Fertig Lab/csv/BreastCancerImmuneAge.csv")


lmListB = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Age"))
  lm = lm(formula, outB)
  lmListB[[i]] = lm
}

Bdat = lapply(lmListB, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(Bdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(Bdat) = higherOrderIC
Bdf = do.call(rbind, Bdat)
Bdf = as.data.frame(Bdf)
Bdf$PAdj = p.adjust(Bdf[,4], "BH")
Bdf
#save
write.csv(Bdf, "~/Fertig Lab/csv/BreastImmuneAge.csv")


#plot
BCstats = unlist(lapply(BCdat, function(x){x[3]}))
Bstats = unlist(lapply(Bdat, function(x){x[3]}))

names(BCstats) = higherOrderIC
names(Bstats) = higherOrderIC

BCStats = as.data.frame(BCstats)

ggplot(BCStats, aes(x=reorder(xnames, -BCstats), y=BCstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for BRCA patients", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
     scale_fill_hue(c=60) +
    theme(legend.position = "none")

BStats = as.data.frame(Bstats)

ggplot(BStats, aes(x=reorder(xnames, -Bstats), y=Bstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for GTEx breast Samples", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
   scale_fill_hue(c=60) +
    theme(legend.position = "none")

## Colon

colonCancer = mixDataSub[which(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym == "COAD") ,]

colonGtex = Gtex[which(Gtex$Tissue == "Colon"),]

outCC = higherOrderImmuneTypes(colonCancer)
outC = higherOrderImmuneTypes(colonGtex)

lmListCC = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Diagnosis.Age"))
  lm = lm(formula, outCC)
  lmListCC[[i]] = lm
}

CCdat = lapply(lmListCC, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(CCdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(CCdat) = higherOrderIC
CCdf = do.call(rbind, CCdat)
CCdf = as.data.frame(CCdf)
CCdf$PAdj = p.adjust(CCdf[,4], "BH")
CCdf

#save
write.csv(CCdf, "~/Fertig Lab/csv/ColonCancerImmuneAge.csv")


lmListC = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Age"))
  lm = lm(formula, outC)
  lmListC[[i]] = lm
}

Cdat = lapply(lmListC, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(Cdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(Cdat) = higherOrderIC
Cdf = do.call(rbind, Cdat)
Cdf = as.data.frame(Cdf)
Cdf$PAdj = p.adjust(Cdf[,4], "BH")
Cdf
#save
write.csv(Cdf, "~/Fertig Lab/csv/ColonImmuneAge.csv")


#plot
CCstats = unlist(lapply(CCdat, function(x){x[3]}))
Cstats = unlist(lapply(Cdat, function(x){x[3]}))

names(CCstats) = higherOrderIC
names(Cstats) = higherOrderIC

CCStats = as.data.frame(CCstats)

ggplot(CCStats, aes(x=reorder(xnames, -CCstats), y=CCstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for COAD patients", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
     scale_fill_hue(c=60) +
    theme(legend.position = "none")

CStats = as.data.frame(Cstats)

ggplot(CStats, aes(x=reorder(xnames, -Cstats), y=Cstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for GTEx colon Samples", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
   scale_fill_hue(c=60) +
    theme(legend.position = "none")

#Esophagus

esoCancer = mixDataSub[which(mixDataSub$TCGA.PanCanAtlas.Cancer.Type.Acronym == "ESCA") ,]

esoGtex = Gtex[which(Gtex$Tissue == "Esophagus"),]

outEC = higherOrderImmuneTypes(esoCancer)
outE = higherOrderImmuneTypes(esoGtex)

lmListEC = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Diagnosis.Age"))
  lm = lm(formula, outEC)
  lmListEC[[i]] = lm
}

ECdat = lapply(lmListEC, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(ECdat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(ECdat) = higherOrderIC
ECdf = do.call(rbind, ECdat)
ECdf = as.data.frame(ECdf)
ECdf$PAdj = p.adjust(ECdf[,4], "BH")
ECdf

#save
write.csv(ECdf, "~/Fertig Lab/csv/EsophagealCancerImmuneAge.csv")


lmListE = vector("list", length(higherOrderIC))
for(i in seq_along(higherOrderIC)) {
  formula = as.formula(paste(higherOrderIC[i], "~ Age"))
  lm = lm(formula, outE)
  lmListE[[i]] = lm
}

Edat = lapply(lmListE, function(x) {summary(x)$coefficients[2,]})
pvals = unlist(lapply(Edat, function(x){x[4]}))
agePvals = cbind(higherOrderIC, pvals, p.adjust(pvals, "BH"))
agePvals[order(pvals),]

names(Edat) = higherOrderIC
Edf = do.call(rbind, Edat)
Edf = as.data.frame(Edf)
Edf$PAdj = p.adjust(Edf[,4], "BH")
Edf
#save
write.csv(Edf, "~/Fertig Lab/csv/EsophagusImmuneAge.csv")


#plot
ECstats = unlist(lapply(ECdat, function(x){x[3]}))
Estats = unlist(lapply(Edat, function(x){x[3]}))

names(ECstats) = higherOrderIC
names(Estats) = higherOrderIC

ECStats = as.data.frame(ECstats)

ggplot(ECStats, aes(x=reorder(xnames, -ECstats), y=ECstats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for ESCA patients", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
     scale_fill_hue(c=60) +
    theme(legend.position = "none")

EStats = as.data.frame(Estats)

ggplot(EStats, aes(x=reorder(xnames, -Estats), y=Estats, fill = reorder(xnames, -LCstats))) +
    geom_bar(stat="identity")+
    labs(title="Relationship of Age and Immune Infiltration for GTEx esophageal Samples", x="Cell Type", y = "T Statistic")+
    theme_minimal()+
   scale_fill_hue(c=60) +
    theme(legend.position = "none")

```


HNSC and HPV
```{r}
HNSC = indvCancerDataList3$HNSC

hpvStatus = readRDS("Data/hpvHNSC.rds")

length(which(HNSC$Patient.ID %in% hpvStatus$`HNSCC Barcode`))

#remove HPV positive patients and see if results change
HNSCnoHPV = HNSC[-which(HNSC$Patient.ID %in% hpvStatus$`HNSCC Barcode`),]

HNSCHPV = HNSC[which(HNSC$Patient.ID %in% hpvStatus$`HNSCC Barcode`),]


runLmAgeImmune(HNSCnoHPV)
runLmAgeImmune(HNSCHPV)
runLmAgeImmune(HNSC)

coxph_model_mixture(higherOrderImmuneTypes(HNSCnoHPV), time = "Overall.Survival..Months.", event = "Overall.Survival.Status", covars = "Sex + Diagnosis.Age + SmokingYears", startcolumn = 46, endcolumn = 51)

coxph_model_mixture(higherOrderImmuneTypes(HNSCHPV), time = "Overall.Survival..Months.", event = "Overall.Survival.Status", covars = "Sex + Diagnosis.Age", startcolumn = 46, endcolumn = 51)

coxph_model_mixture(higherOrderImmuneTypes(HNSC), time = "Overall.Survival..Months.", event = "Overall.Survival.Status", covars = "Sex + Diagnosis.Age", startcolumn = 46, endcolumn = 51)
```


